#include<stdio.h>
#include<conio.h>

main()

{
     int a=10 , b=5;

     clrscr();

     printf("%d+%d = %d\n",a,b,a+b);
     printf("%d-%d = %d\n",a,b,a-b);
     printf("%d*%d= %d\n",a,b,a*b);
     printf("%d%%d= %d\n",a,b,a%b);

     printf("\n\n");


     printf("a value of %d and b value sum of %d\n", a,b,a+b);
     printf("a value of %d and b value substraction of%d\n",a,b,a-b);
     printf("a value of %d and b value product of %d\n",a,b,a*b);
     printf("a value of %d and b value division of %d\n",a,b,a%b);




     getch();













}